# Generated by Django 6.0.5 on 2026-05-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=20, unique=True, verbose_name='ID Paciente')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('IMC', models.FloatField(blank=True, null=True, verbose_name='IMC')),
                ('presion_sistolica', models.IntegerField(verbose_name='Presión Sistólica')),
                ('presion_diastolica', models.IntegerField(verbose_name='Presión Diastólica')),
                ('frecuencia_cardiaca', models.IntegerField(verbose_name='Frecuencia Cardíaca')),
                ('glucosa', models.FloatField(verbose_name='Glucosa')),
                ('colesterol', models.FloatField(verbose_name='Colesterol')),
                ('saturacion_oxigeno', models.FloatField(verbose_name='Saturación Oxígeno')),
                ('temperatura', models.FloatField(verbose_name='Temperatura')),
                ('antecedentes_familiares', models.CharField(blank=True, max_length=200, null=True, verbose_name='Antecedentes Familiares')),
                ('fumador', models.CharField(max_length=2, verbose_name='Fumador')),
                ('consumo_alcohol', models.CharField(max_length=2, verbose_name='Consumo Alcohol')),
                ('actividad_fisica', models.CharField(max_length=50, verbose_name='Actividad Física')),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnóstico Preliminar')),
                ('riesgo_enfermedad', models.CharField(max_length=20, verbose_name='Riesgo Enfermedad')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_predicho', models.CharField(max_length=20, verbose_name='Riesgo Predicho')),
                ('probabilidad', models.FloatField(verbose_name='Probabilidad')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Clínico',
                'verbose_name_plural': 'Registros Clínicos',
            },
        ),
    ]
