# Generated by Django 6.0.6 on 2026-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagiousDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Enfermedad Contagiosa',
                'verbose_name_plural': 'Enfermedades Contagiosas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_contagiosas',
            field=models.ManyToManyField(blank=True, to='core.contagiousdisease', verbose_name='Enfermedades Contagiosas'),
        ),
    ]
