# Generated by Django 6.0.6 on 2026-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contagiousdisease_paciente_enfermedades_contagiosas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Hospitalizado', 'Hospitalizado'), ('Dado de Alta', 'Dado de Alta'), ('Fallecido', 'Fallecido')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
    ]
