# Generated by Django 6.0.6 on 2026-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente_estado_paciente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='necesidades_cuidado',
            field=models.TextField(blank=True, help_text='Ej: Oxígeno, Cambio de suero, Medicación, Monitoreo constante, etc.', null=True, verbose_name='Necesidades de Cuidado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='piso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ubicacion',
            field=models.CharField(choices=[('Urgencias', 'Urgencias'), ('Hospitalización', 'Hospitalización'), ('UCI', 'UCI'), ('Cirugía', 'Cirugía'), ('Consulta Externa', 'Consulta Externa')], default='Consulta Externa', max_length=50, verbose_name='Ubicación'),
        ),
    ]
