# Generated by Django 6.0.5 on 2026-05-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.CharField(max_length=255, verbose_name='Archivo')),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_limpios', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.FloatField(default=0, verbose_name='Tiempo ejecución (s)')),
                ('estado', models.CharField(default='Completado', max_length=20, verbose_name='Estado')),
                ('logs', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial ETL',
                'verbose_name_plural': 'Historiales ETL',
                'ordering': ['-fecha'],
            },
        ),
    ]
